package so.microcloud.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CustomerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public CustomerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNull() {
			addCriterion("shop_name is null");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNotNull() {
			addCriterion("shop_name is not null");
			return (Criteria) this;
		}

		public Criteria andShopNameEqualTo(String value) {
			addCriterion("shop_name =", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotEqualTo(String value) {
			addCriterion("shop_name <>", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThan(String value) {
			addCriterion("shop_name >", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThanOrEqualTo(String value) {
			addCriterion("shop_name >=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThan(String value) {
			addCriterion("shop_name <", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThanOrEqualTo(String value) {
			addCriterion("shop_name <=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLike(String value) {
			addCriterion("shop_name like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotLike(String value) {
			addCriterion("shop_name not like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameIn(List<String> values) {
			addCriterion("shop_name in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotIn(List<String> values) {
			addCriterion("shop_name not in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameBetween(String value1, String value2) {
			addCriterion("shop_name between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotBetween(String value1, String value2) {
			addCriterion("shop_name not between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameIsNull() {
			addCriterion("customer_name is null");
			return (Criteria) this;
		}

		public Criteria andCustomerNameIsNotNull() {
			addCriterion("customer_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerNameEqualTo(String value) {
			addCriterion("customer_name =", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotEqualTo(String value) {
			addCriterion("customer_name <>", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameGreaterThan(String value) {
			addCriterion("customer_name >", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
			addCriterion("customer_name >=", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameLessThan(String value) {
			addCriterion("customer_name <", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameLessThanOrEqualTo(String value) {
			addCriterion("customer_name <=", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameLike(String value) {
			addCriterion("customer_name like", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotLike(String value) {
			addCriterion("customer_name not like", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameIn(List<String> values) {
			addCriterion("customer_name in", values, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotIn(List<String> values) {
			addCriterion("customer_name not in", values, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameBetween(String value1, String value2) {
			addCriterion("customer_name between", value1, value2, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotBetween(String value1, String value2) {
			addCriterion("customer_name not between", value1, value2, "customerName");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andTypeIdIsNull() {
			addCriterion("type_id is null");
			return (Criteria) this;
		}

		public Criteria andTypeIdIsNotNull() {
			addCriterion("type_id is not null");
			return (Criteria) this;
		}

		public Criteria andTypeIdEqualTo(Integer value) {
			addCriterion("type_id =", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotEqualTo(Integer value) {
			addCriterion("type_id <>", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdGreaterThan(Integer value) {
			addCriterion("type_id >", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("type_id >=", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLessThan(Integer value) {
			addCriterion("type_id <", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLessThanOrEqualTo(Integer value) {
			addCriterion("type_id <=", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdIn(List<Integer> values) {
			addCriterion("type_id in", values, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotIn(List<Integer> values) {
			addCriterion("type_id not in", values, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdBetween(Integer value1, Integer value2) {
			addCriterion("type_id between", value1, value2, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("type_id not between", value1, value2, "typeId");
			return (Criteria) this;
		}

		public Criteria andProductIsNull() {
			addCriterion("product is null");
			return (Criteria) this;
		}

		public Criteria andProductIsNotNull() {
			addCriterion("product is not null");
			return (Criteria) this;
		}

		public Criteria andProductEqualTo(String value) {
			addCriterion("product =", value, "product");
			return (Criteria) this;
		}

		public Criteria andProductNotEqualTo(String value) {
			addCriterion("product <>", value, "product");
			return (Criteria) this;
		}

		public Criteria andProductGreaterThan(String value) {
			addCriterion("product >", value, "product");
			return (Criteria) this;
		}

		public Criteria andProductGreaterThanOrEqualTo(String value) {
			addCriterion("product >=", value, "product");
			return (Criteria) this;
		}

		public Criteria andProductLessThan(String value) {
			addCriterion("product <", value, "product");
			return (Criteria) this;
		}

		public Criteria andProductLessThanOrEqualTo(String value) {
			addCriterion("product <=", value, "product");
			return (Criteria) this;
		}

		public Criteria andProductLike(String value) {
			addCriterion("product like", value, "product");
			return (Criteria) this;
		}

		public Criteria andProductNotLike(String value) {
			addCriterion("product not like", value, "product");
			return (Criteria) this;
		}

		public Criteria andProductIn(List<String> values) {
			addCriterion("product in", values, "product");
			return (Criteria) this;
		}

		public Criteria andProductNotIn(List<String> values) {
			addCriterion("product not in", values, "product");
			return (Criteria) this;
		}

		public Criteria andProductBetween(String value1, String value2) {
			addCriterion("product between", value1, value2, "product");
			return (Criteria) this;
		}

		public Criteria andProductNotBetween(String value1, String value2) {
			addCriterion("product not between", value1, value2, "product");
			return (Criteria) this;
		}

		public Criteria andIsPublicIsNull() {
			addCriterion("is_public is null");
			return (Criteria) this;
		}

		public Criteria andIsPublicIsNotNull() {
			addCriterion("is_public is not null");
			return (Criteria) this;
		}

		public Criteria andIsPublicEqualTo(Integer value) {
			addCriterion("is_public =", value, "isPublic");
			return (Criteria) this;
		}

		public Criteria andIsPublicNotEqualTo(Integer value) {
			addCriterion("is_public <>", value, "isPublic");
			return (Criteria) this;
		}

		public Criteria andIsPublicGreaterThan(Integer value) {
			addCriterion("is_public >", value, "isPublic");
			return (Criteria) this;
		}

		public Criteria andIsPublicGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_public >=", value, "isPublic");
			return (Criteria) this;
		}

		public Criteria andIsPublicLessThan(Integer value) {
			addCriterion("is_public <", value, "isPublic");
			return (Criteria) this;
		}

		public Criteria andIsPublicLessThanOrEqualTo(Integer value) {
			addCriterion("is_public <=", value, "isPublic");
			return (Criteria) this;
		}

		public Criteria andIsPublicIn(List<Integer> values) {
			addCriterion("is_public in", values, "isPublic");
			return (Criteria) this;
		}

		public Criteria andIsPublicNotIn(List<Integer> values) {
			addCriterion("is_public not in", values, "isPublic");
			return (Criteria) this;
		}

		public Criteria andIsPublicBetween(Integer value1, Integer value2) {
			addCriterion("is_public between", value1, value2, "isPublic");
			return (Criteria) this;
		}

		public Criteria andIsPublicNotBetween(Integer value1, Integer value2) {
			addCriterion("is_public not between", value1, value2, "isPublic");
			return (Criteria) this;
		}

		public Criteria andClaimUserIsNull() {
			addCriterion("claim_user is null");
			return (Criteria) this;
		}

		public Criteria andClaimUserIsNotNull() {
			addCriterion("claim_user is not null");
			return (Criteria) this;
		}

		public Criteria andClaimUserEqualTo(Integer value) {
			addCriterion("claim_user =", value, "claimUser");
			return (Criteria) this;
		}

		public Criteria andClaimUserNotEqualTo(Integer value) {
			addCriterion("claim_user <>", value, "claimUser");
			return (Criteria) this;
		}

		public Criteria andClaimUserGreaterThan(Integer value) {
			addCriterion("claim_user >", value, "claimUser");
			return (Criteria) this;
		}

		public Criteria andClaimUserGreaterThanOrEqualTo(Integer value) {
			addCriterion("claim_user >=", value, "claimUser");
			return (Criteria) this;
		}

		public Criteria andClaimUserLessThan(Integer value) {
			addCriterion("claim_user <", value, "claimUser");
			return (Criteria) this;
		}

		public Criteria andClaimUserLessThanOrEqualTo(Integer value) {
			addCriterion("claim_user <=", value, "claimUser");
			return (Criteria) this;
		}

		public Criteria andClaimUserIn(List<Integer> values) {
			addCriterion("claim_user in", values, "claimUser");
			return (Criteria) this;
		}

		public Criteria andClaimUserNotIn(List<Integer> values) {
			addCriterion("claim_user not in", values, "claimUser");
			return (Criteria) this;
		}

		public Criteria andClaimUserBetween(Integer value1, Integer value2) {
			addCriterion("claim_user between", value1, value2, "claimUser");
			return (Criteria) this;
		}

		public Criteria andClaimUserNotBetween(Integer value1, Integer value2) {
			addCriterion("claim_user not between", value1, value2, "claimUser");
			return (Criteria) this;
		}

		public Criteria andClaimTimeIsNull() {
			addCriterion("claim_time is null");
			return (Criteria) this;
		}

		public Criteria andClaimTimeIsNotNull() {
			addCriterion("claim_time is not null");
			return (Criteria) this;
		}

		public Criteria andClaimTimeEqualTo(Date value) {
			addCriterion("claim_time =", value, "claimTime");
			return (Criteria) this;
		}

		public Criteria andClaimTimeNotEqualTo(Date value) {
			addCriterion("claim_time <>", value, "claimTime");
			return (Criteria) this;
		}

		public Criteria andClaimTimeGreaterThan(Date value) {
			addCriterion("claim_time >", value, "claimTime");
			return (Criteria) this;
		}

		public Criteria andClaimTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("claim_time >=", value, "claimTime");
			return (Criteria) this;
		}

		public Criteria andClaimTimeLessThan(Date value) {
			addCriterion("claim_time <", value, "claimTime");
			return (Criteria) this;
		}

		public Criteria andClaimTimeLessThanOrEqualTo(Date value) {
			addCriterion("claim_time <=", value, "claimTime");
			return (Criteria) this;
		}

		public Criteria andClaimTimeIn(List<Date> values) {
			addCriterion("claim_time in", values, "claimTime");
			return (Criteria) this;
		}

		public Criteria andClaimTimeNotIn(List<Date> values) {
			addCriterion("claim_time not in", values, "claimTime");
			return (Criteria) this;
		}

		public Criteria andClaimTimeBetween(Date value1, Date value2) {
			addCriterion("claim_time between", value1, value2, "claimTime");
			return (Criteria) this;
		}

		public Criteria andClaimTimeNotBetween(Date value1, Date value2) {
			addCriterion("claim_time not between", value1, value2, "claimTime");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("create_user is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("create_user is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(Integer value) {
			addCriterion("create_user =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(Integer value) {
			addCriterion("create_user <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(Integer value) {
			addCriterion("create_user >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_user >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(Integer value) {
			addCriterion("create_user <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
			addCriterion("create_user <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<Integer> values) {
			addCriterion("create_user in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<Integer> values) {
			addCriterion("create_user not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(Integer value1, Integer value2) {
			addCriterion("create_user between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
			addCriterion("create_user not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("state is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("state is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(Integer value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(Integer value) {
			addCriterion("state <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(Integer value) {
			addCriterion("state >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("state >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(Integer value) {
			addCriterion("state <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(Integer value) {
			addCriterion("state <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<Integer> values) {
			addCriterion("state in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<Integer> values) {
			addCriterion("state not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(Integer value1, Integer value2) {
			addCriterion("state between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(Integer value1, Integer value2) {
			addCriterion("state not between", value1, value2, "state");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_customer
     *
     * @mbg.generated do_not_delete_during_merge Sat Apr 11 22:16:03 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}