package so.microcloud.bean;

import java.io.Serializable;
import java.util.Date;

public class CustomerContact implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_contact.id
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_contact.customer_id
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_contact.content
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_contact.type_id
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	private Integer typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_contact.create_user
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	private Integer createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_contact.create_time
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_contact.last_modify_time
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	private Date lastModifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_contact.state
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_customer_contact
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_contact.id
	 * @return  the value of t_customer_contact.id
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_contact.id
	 * @param id  the value for t_customer_contact.id
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_contact.customer_id
	 * @return  the value of t_customer_contact.customer_id
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_contact.customer_id
	 * @param customerId  the value for t_customer_contact.customer_id
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_contact.content
	 * @return  the value of t_customer_contact.content
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_contact.content
	 * @param content  the value for t_customer_contact.content
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_contact.type_id
	 * @return  the value of t_customer_contact.type_id
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_contact.type_id
	 * @param typeId  the value for t_customer_contact.type_id
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_contact.create_user
	 * @return  the value of t_customer_contact.create_user
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_contact.create_user
	 * @param createUser  the value for t_customer_contact.create_user
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_contact.create_time
	 * @return  the value of t_customer_contact.create_time
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_contact.create_time
	 * @param createTime  the value for t_customer_contact.create_time
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_contact.last_modify_time
	 * @return  the value of t_customer_contact.last_modify_time
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public Date getLastModifyTime() {
		return lastModifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_contact.last_modify_time
	 * @param lastModifyTime  the value for t_customer_contact.last_modify_time
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public void setLastModifyTime(Date lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_contact.state
	 * @return  the value of t_customer_contact.state
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_contact.state
	 * @param state  the value for t_customer_contact.state
	 * @mbg.generated  Sat Apr 25 12:40:17 CST 2020
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	private String createUserName;

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}
    
}