package so.microcloud.bean;

import java.io.Serializable;
import java.util.Date;

public class Customer implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.id
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.shop_name
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private String shopName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.customer_name
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private String customerName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.phone
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.type_id
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private Integer typeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.product
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private String product;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.is_public
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private Integer isPublic;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.claim_user
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private Integer claimUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.claim_time
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private Date claimTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.create_user
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private Integer createUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.create_time
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer.state
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private Integer state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.id
	 * @return  the value of t_customer.id
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.id
	 * @param id  the value for t_customer.id
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.shop_name
	 * @return  the value of t_customer.shop_name
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.shop_name
	 * @param shopName  the value for t_customer.shop_name
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.customer_name
	 * @return  the value of t_customer.customer_name
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.customer_name
	 * @param customerName  the value for t_customer.customer_name
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.phone
	 * @return  the value of t_customer.phone
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.phone
	 * @param phone  the value for t_customer.phone
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.type_id
	 * @return  the value of t_customer.type_id
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.type_id
	 * @param typeId  the value for t_customer.type_id
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.product
	 * @return  the value of t_customer.product
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public String getProduct() {
		return product;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.product
	 * @param product  the value for t_customer.product
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setProduct(String product) {
		this.product = product;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.is_public
	 * @return  the value of t_customer.is_public
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public Integer getIsPublic() {
		return isPublic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.is_public
	 * @param isPublic  the value for t_customer.is_public
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setIsPublic(Integer isPublic) {
		this.isPublic = isPublic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.claim_user
	 * @return  the value of t_customer.claim_user
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public Integer getClaimUser() {
		return claimUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.claim_user
	 * @param claimUser  the value for t_customer.claim_user
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setClaimUser(Integer claimUser) {
		this.claimUser = claimUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.claim_time
	 * @return  the value of t_customer.claim_time
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public Date getClaimTime() {
		return claimTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.claim_time
	 * @param claimTime  the value for t_customer.claim_time
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setClaimTime(Date claimTime) {
		this.claimTime = claimTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.create_user
	 * @return  the value of t_customer.create_user
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.create_user
	 * @param createUser  the value for t_customer.create_user
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.create_time
	 * @return  the value of t_customer.create_time
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.create_time
	 * @param createTime  the value for t_customer.create_time
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer.state
	 * @return  the value of t_customer.state
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer.state
	 * @param state  the value for t_customer.state
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	private String typeName;
    
    private String createUserName;
    
    private String claimUserName;
    
	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public String getClaimUserName() {
		return claimUserName;
	}

	public void setClaimUserName(String claimUserName) {
		this.claimUserName = claimUserName;
	}

}