package so.microcloud.bean;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_user.id
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_user.user_name
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_user.nick_name
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	private String nickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_user.phone
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_user.password
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_user.is_admin
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	private Integer isAdmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_user.create_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	private Integer createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_user.create_time
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_user.state
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_user.id
	 * @return  the value of t_sys_user.id
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_user.id
	 * @param id  the value for t_sys_user.id
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_user.user_name
	 * @return  the value of t_sys_user.user_name
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_user.user_name
	 * @param userName  the value for t_sys_user.user_name
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_user.nick_name
	 * @return  the value of t_sys_user.nick_name
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_user.nick_name
	 * @param nickName  the value for t_sys_user.nick_name
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_user.phone
	 * @return  the value of t_sys_user.phone
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_user.phone
	 * @param phone  the value for t_sys_user.phone
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_user.password
	 * @return  the value of t_sys_user.password
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_user.password
	 * @param password  the value for t_sys_user.password
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_user.is_admin
	 * @return  the value of t_sys_user.is_admin
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public Integer getIsAdmin() {
		return isAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_user.is_admin
	 * @param isAdmin  the value for t_sys_user.is_admin
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public void setIsAdmin(Integer isAdmin) {
		this.isAdmin = isAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_user.create_user
	 * @return  the value of t_sys_user.create_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public Integer getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_user.create_user
	 * @param createUser  the value for t_sys_user.create_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_user.create_time
	 * @return  the value of t_sys_user.create_time
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_user.create_time
	 * @param createTime  the value for t_sys_user.create_time
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_user.state
	 * @return  the value of t_sys_user.state
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_user.state
	 * @param state  the value for t_sys_user.state
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	public void setState(Integer state) {
		this.state = state;
	}
	
    private String todayCount;
    
    private String monthCount;

	public String getTodayCount() {
		return todayCount;
	}

	public void setTodayCount(String todayCount) {
		this.todayCount = todayCount;
	}

	public String getMonthCount() {
		return monthCount;
	}

	public void setMonthCount(String monthCount) {
		this.monthCount = monthCount;
	}
    
}