package so.microcloud.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import so.microcloud.bean.Customer;
import so.microcloud.bean.CustomerExample;
import so.microcloud.bean.User;
import so.microcloud.common.PageInfo;

public interface CustomerMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	long countByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	int deleteByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	int insert(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	int insertSelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	List<Customer> selectByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	Customer selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	int updateByPrimaryKeySelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer
	 * @mbg.generated  Thu Apr 16 14:01:38 CST 2020
	 */
	int updateByPrimaryKey(Customer record);

	List<Customer> getPublicCustomerList(@Param("typeId")Integer typeId, @Param("keyword")String keyword, 
			@Param("user")User user, @Param("pageInfo")PageInfo pageInfo);
	
	List<Customer> getCustomerList(@Param("typeId")Integer typeId, @Param("keyword")String keyword, 
			@Param("user")User user, @Param("pageInfo")PageInfo pageInfo);
}