package so.microcloud.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import so.microcloud.bean.CustomerType;
import so.microcloud.bean.CustomerTypeExample;

public interface CustomerTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    long countByExample(CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    int deleteByExample(CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    int insert(CustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    int insertSelective(CustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    List<CustomerType> selectByExample(CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    CustomerType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerType record, @Param("example") CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    int updateByExample(@Param("record") CustomerType record, @Param("example") CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_type
     *
     * @mbg.generated Sun Apr 12 00:01:45 CST 2020
     */
    int updateByPrimaryKey(CustomerType record);
}