package so.microcloud.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import so.microcloud.bean.User;
import so.microcloud.bean.UserExample;
import so.microcloud.common.PageInfo;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	int updateByExample(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
	 * @mbg.generated  Sat Apr 11 18:19:56 CST 2020
	 */
	int updateByPrimaryKey(User record);
	
	List<User> getUserList(@Param("keyword")String keyword, @Param("pageInfo")PageInfo pageInfo);
	
	List<User> getContactStatistics(@Param("keyword")String keyword, @Param("pageInfo")PageInfo pageInfo);
	
}